name: Terraform Plan

on:
  pull_request:
    branches: [main]
    paths:
      - "envs/**"
      - "modules/**"
      - "functions/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    strategy:
      matrix:
        env: [dev, prod]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=terraform.tfvars -no-color
        continue-on-error: true

      - name: Comment plan on PR
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan – ${{ matrix.env }}
            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output,
            })

      - name: Fail if plan failed
        if: steps.plan.outcome == 'failure'
        run: exit 1
