name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - "envs/**"
      - "modules/**"
      - "functions/**"

permissions:
  id-token: write
  contents: read

jobs:
  apply-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/dev
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-north-1

      - run: terraform init
      - run: terraform apply -var-file=terraform.tfvars -auto-approve

  get-id-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - run: |
          ID_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://demo" | jq -r .value)
          echo $ID_TOKEN | base64

  apply-prod:
    needs: apply-dev
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: envs/prod
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: eu-north-1

      - run: terraform init
      - run: terraform apply -var-file=terraform.tfvars -auto-approve
